#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd net.frontuari.importdataprocess.targetplatform
./plugin-builder $DEBUG_MODE ../net.frontuari.importdataprocess ../net.frontuari.importdataprocess.test
